### ISSUE TITLE
Property '$geolocation' does not exist on type

### ISSUE THREAD

**Issue by EmilM32** [SkyaTura/vue-geolocation-api#10]
I'm using geolocation on nuxt with typescript. When i try to get coords i got an error `Property '$geolocation' does not exist on type 'Main'` - Main is the name of my class (i'm using nuxt-property-decorator).

**Comment by SkyaTura** [comment]
Sorry, I don't have any experience with TypeScript and Vue, but I'll take a look as soon as possible

**Comment by SkyaTura** [comment]
Could you provide some example of your use case so that I can reproduce locally?

I tried with a fresh install of nuxt + TypeScript but worked perfectly.

**Comment by EmilM32** [comment]
This is my class
```<script lang="ts">
import { Vue, Component, Watch } from "nuxt-property-decorator";

@Component
export default class Main extends Vue {
  mounted() {
    console.log(this.$geolocation.coords);
  }
}
</script>
```

And this is an error in console
```
 ERROR  ERROR in pages/index.vue:13:22                                                                                17:46:00
TS2339: Property '$geolocation' does not exist on type 'Main'.
    11 | export default class Main extends Vue {
    12 |   mounted() {
  > 13 |     console.log(this.$geolocation.coords);
       |                      ^^^^^^^^^^^^
    14 |   }
    15 | }
    16 | </script>

```

**Comment by SkyaTura** [comment]
Sorry for the delay, these weeks has been hard...

I could not reproduce your problem, can you provide a dummy repository with the bare minimum to test it?

I want to solve this problem before the new year 😄

**Comment by EmilM32** [comment]
I used it here: [repo](https://github.com/EmilM32/weather-app)

**Comment by SkyaTura** [comment]
@EmilM32 please update to the latest version (0.1.21) and add `"vue-geolocation-api"` to your `types` section of the *tsconfig.json* file.

![image](https://user-images.githubusercontent.com/6800723/103449328-6859a980-4c85-11eb-8579-e854f9ad2902.png)

Thank you for your issue.
